version: '3.1'

services:
  mercure:
    image: dunglas/mercure
    command: caddy run -config /etc/caddy/Caddyfile.dev
    ports: ['3000:80', '3443:443']
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://127.0.0.1:8000